# spring.cloud.config.server.git.uri=https://github.com/CintiaMoon/Microservice-Landscape/Landscape-config-repo
spring:
  cloud:
    config:
      server:
        git.uri : file:/workspaces/Technologies/Microservice-Landscape/Microservice-Landscape/Landscape-config-repo

server:
  port: 8888


#logging:
#  path: logs
#  logging:
#    file :  logs/Landscape-Config-Server.log		
#    logging:
#      pattern.file : '%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n'

      
logging:
  file: logs/Landscape-Config-Server.log    
  pattern:
    file: '%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n'
  level:
    org.springframework.web: INFO
    com.cargain.micro.landscape.config: DEBUG
    