spring:
  cloud:
   config:
      server:
        git.uri : file:/temp/monitoring/Landscape-config-repo
        #git.uri : https://github.com/CintiaMoon/Landscape-config-repo.git

server:
  port: 8888

     
logging:
  file: logs/Landscape-Config-Server.log    
  pattern:
    file: '%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n'
  level:
    org.springframework.web: INFO
    com.cargain.micro.landscape.config: DEBUG

