 
INSERT INTO EMPLOYEE (EMP_ID, NAME) VALUES ('1','John');
INSERT INTO EMPLOYEE (EMP_ID, NAME) VALUES ('2','Mary');
INSERT INTO EMPLOYEE (EMP_ID, NAME) VALUES ('3','Peter');
INSERT INTO EMPLOYEE (EMP_ID, NAME) VALUES ('4','Carl');
INSERT INTO EMPLOYEE (EMP_ID, NAME) VALUES ('5','Adam');


INSERT INTO EMPLOYEE_ADDRESS (ADDR_ID, EMP_ID, STREET, CITY, STATE, COUNTRY) VALUES (1,1,'10700 Westside Road','Alpharetta','GA', 'US');
INSERT INTO EMPLOYEE_ADDRESS (ADDR_ID, EMP_ID, STREET, CITY, STATE, COUNTRY) VALUES (2,2,'1075 Holcomb Bridge Road','Roswell','GA', 'US');
INSERT INTO EMPLOYEE_ADDRESS (ADDR_ID, EMP_ID, STREET, CITY, STATE, COUNTRY) VALUES (3,3,'321 West Bay Street','Savannah','GA', 'US');
INSERT INTO EMPLOYEE_ADDRESS (ADDR_ID, EMP_ID, STREET, CITY, STATE, COUNTRY) VALUES (4,4,'500 Powder Springs St','Marietta','GA', 'US');
INSERT INTO EMPLOYEE_ADDRESS (ADDR_ID, EMP_ID, STREET, CITY, STATE, COUNTRY) VALUES (5,5,'255 Courtland Street NE','Atlanta','GA', 'US');