CREATE TABLE EMPLOYEE 
 ( EMP_ID NUMBER(10,0) NOT NULL ENABLE, 
 NAME VARCHAR2(255 CHAR), 
 PRIMARY KEY (EMP_ID)
 );
 
 CREATE TABLE EMPLOYEE_ADDRESS 
 ( 
 ADDR_ID NUMBER(10,0) NOT NULL ENABLE, 
 EMP_ID NUMBER(10,0) NOT NULL ENABLE, 
 STREET VARCHAR2(255 CHAR), 
 CITY VARCHAR2(255 CHAR), 
 STATE VARCHAR2(255 CHAR), 
 COUNTRY VARCHAR2(255 CHAR), 

 PRIMARY KEY (ADDR_ID),
 
 CONSTRAINT fk_emp FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID)
 );
